[[mgr.prepend_keymap]]
on   = "<C-w>"
run  = "close"
desc = "Close the current tab, or quit if its last"

[[mgr.prepend_keymap]]
on   = "<C-c>"
run  = "noop"

[[mgr.prepend_keymap]]
on   = "q"
run  = "quit --no-cwd-file"
desc = "Quit without outputting cwd-file"

[[mgr.prepend_keymap]]
on   = "Q"
run  = "quit"
desc = "Quit the process"
